### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by tomshane** [ghengeveld/react-async#10]
Hello,

is there a plan for official typescript support?

Thanks.

**Comment by ghengeveld** [comment]
I've been thinking of adding a typings file, yes.

**Comment by tomshane** [comment]
That would be great. I find the library very useful and easy to use and with typings it would be complete. :) Thanks.

**Comment by nealeu** [comment]
It looks like two of us got to the same point and acted.  I was working on mine in a gist via enhancing react-async to be a .tsx file to check it worked.

That can all be found here: https://gist.github.com/nealeu/23ee4919fab5ad0a776d1d741bb556a5.

I'd intended to get a pull request in too.  Above is in case I've solved some issues that are not addressed.  

I'll endeavour to review and PR anything I spot if I get the chance.

**Comment by ghengeveld** [comment]
I'll take a look at your typings. It's been a while since I tried to tackle them, but still haven't succeeded at producing a typings file that could deal with the compound helper components. I opened a StackOverflow question but that still hasn't yielded a working solution. https://stackoverflow.com/questions/53564005/correct-type-definition-for-a-react-class-with-static-member-components

**Comment by ghengeveld** [comment]
Typings should be good now. There's a [v4](https://github.com/ghengeveld/react-async/tree/v4) coming up with API changes to improve compatibility with TypeScript, specifically to avoid spread params at the start of the arguments list in `deferFn`.

**Comment by ghengeveld** [comment]
Hey @tomshane and @nealeu I just created a pre-release for #37 which greatly improves usability with TypeScript. You can install it as `react-async@6.0.0-0` or `react-async@next`. It will soon be released, but I'd like to gather some feedback first. Care to take a look and try it out?

**Comment by nealeu** [comment]
I've updated and the first encouraging sign is the failure on my Jest snapshot

`    -       </AsyncReferralAndClient.Loading>
    -       <AsyncReferralAndClient.Resolved />
    +       </AsyncReferralAndClient.Pending>
    +       <AsyncReferralAndClient.Fulfilled />
 `

With that updated, the build runs fine.

**Comment by ghengeveld** [comment]
Excellent. Be aware that I'm changing `waiting` to `initial` in the final v6 release (as opposed to the pre-release).

**Comment by nealeu** [comment]
Thanks.  Yes that's not a problem.

**Comment by tomshane** [comment]
Hey @ghengeveld, I'm currently using only hooks API of the Async in my project, which already works fine with the Typescript, but I'm gonna try the prerelease anyway. Thanks.

**Comment by ghengeveld** [comment]
V6 is released now ;-) In fact the latest version is 6.0.1.

**Comment by yuliia007naumenko** [comment]
I still have an issue: Property 'Fulfilled' does not exist on type '<T>(defaultProps?: AsyncProps<T> | undefined) => Async<T>'.

**Comment by ghengeveld** [comment]
@yuliia007naumenko Could you please share the code that triggers this error?
