### ISSUE TITLE
React DevTools shows components as Unknown

### ISSUE THREAD

**Issue by nealeu** [ghengeveld/react-async#14]
Hi,

I hit the issue of finding various Unknown entries in React DevTools, which would be really useful to have resolved.

My workaround is as follows:

```
export const MyAsyncComponent = createInstance({promiseFn: load});
MyAsyncComponent.displayName = "MyAsyncComponent"; // Because above will render as Unknown
MyAsyncComponent.Resolved.displayName = "Resolved";
```

I think it'd be great to cover this:
createInstance could take an argument 'displayName' to assign to the created component class at the top level, and Resolved/Rejected/Loading could all be hard coded to those names (although "MyAsyncComponent.Resolved" would be clearer)

**Comment by ghengeveld** [comment]
Thanks for reporting! I'm going to look into adding `displayName` as second argument to `createInstance`. I'll also investigate the display name for Async itself, because I expect it won't have one either.

**Comment by ghengeveld** [comment]
Fixed and released in [v3.10.0](https://github.com/ghengeveld/react-async/releases/tag/v3.10.0).

Thanks again for reporting!

**Comment by ghengeveld** [comment]
Here's an example on how to provide a custom displayName with `createInstance`: https://github.com/ghengeveld/react-async/blob/450aad8aff776c80836374539ab7010b906562d4/examples/custom-instance/src/index.js#L11

**Comment by nealeu** [comment]
Many thanks.
