### ISSUE TITLE
Recommended way to test async (instance) components?

### ISSUE THREAD

**Issue by byCedric** [ghengeveld/react-async#17]
Hi Gert!

I'm creating a testing tutorial/workshop for the company I work for and was wondering; what is the recommended way to test created instances of the async component? Is there an easy way to mock/stub/inject a promise or outcome without reference to the `promiseFn` internals?

#### Example
Let's say we have the following code (copied from the read me):

```
import { createInstance } from "react-async"

const loadCustomer = ({ customerId }, { signal }) =>
  fetch(`/api/customers/${customerId}`, { signal })
    .then(res => (res.ok ? res : Promise.reject(res)))
    .then(res => res.json())

// createInstance takes a defaultProps object and a displayName (both optional)
const AsyncCustomer = createInstance({ promiseFn: loadCustomer }, "AsyncCustomer")

const MyComponent = () => (
  <AsyncCustomer customerId={1}>
    <AsyncCustomer.Resolved>{customer => `Hello ${customer.name}`}</AsyncCustomer.Resolved>
  </AsyncCustomer>
)
```

Now, I want to test `MyComponent` that it renders `Hello customer` whenever `AsyncCustomer` successfully resolves. With enzyme, or other React testing tools, I can validate this, and `AsyncCustomer` is being rendered with a `customerId`. But in those tests, I don't want fetch to be executed.

Fetch can be mocked of course to return a certain response, but I'm not sure if there is a better way. When mocking fetch, I'm hardcoding the `promiseFn` implementation. I feel that there should be a better way. Maybe something where it's possible to mock or inject a testing-promise?

Cheers,
Cedric

**Comment by ghengeveld** [comment]
Hey Cedric,

If you want to test your custom instance with predefined promiseFn, it should really be the same as testing the promiseFn itself. And maybe test that you're paying the right props to createInstance. I don't think you should be unit testing the Async instance as a whole. There's already [tests](https://github.com/ghengeveld/react-async/blob/v3.12.0/src/spec.js) for that in place. You're not unit testing React internals either right? If you do still want to test the proper functioning of the whole thing, use integration/smoke testing with something like Cypress or Puppeteer.

Does this answer your question?
Take care.
