### ISSUE TITLE
Typings is not updated 

### ISSUE THREAD

**Issue by Pong420** [ghengeveld/react-async#24]
The arguments order is not updated

```ts
  deferFn?: (props: object, controller: AbortController, args: any[]) => Promise<T>
```

**Comment by ghengeveld** [comment]
Thanks for reporting! This is now fixed in [v4.1.2](https://github.com/ghengeveld/react-async/releases/tag/v4.1.2).

**Comment by ghengeveld** [comment]
Hey @Pong420 I just created a pre-release for #37 which greatly improves usability with TypeScript. You can install it as `react-async@6.0.0-0` or `react-async@next`. It will soon be released, but I'd like to gather some feedback first. Care to take a look and try it out?

**Comment by Pong420** [comment]
It works, thanks.
