### ISSUE TITLE
Async.Deferred to Replace Async.Initial

### ISSUE THREAD

**Issue by dhurlburtusa** [ghengeveld/react-async#40]
Thanks for this library. Very useful.

I know there was some back and forth between `Async.Pending` => `Async.Waiting` and `Async.Initial`. I didn't see any discussion of `Async.Deferred` in any of the conversations (maybe I missed it if it is there).

I know this is too late for the v6.0 release. I didn't think of it until I recently re-read the documentation (README) which states:

> Renders only while the _deferred_ promise is still waiting to be run, or you have not provided any promise.

This component all ties together with `promise`, `deferFn`, and `run`. So, it dawned on me that `Async.Deferred` might be a more suitable name over `Async.Initial`. Can also add in `isDeferred` to alias or take the place of `isInitial`.

This could be added (keeping `Async.Initial` and `isInitial` around for backwards compatibility) to a minor release in v6.x or it could wait until v7.x.

Thoughts?

```
<Async deferFn={this.submitIt}>
  <Async.Deferred>
    <p>I am rendered until a promise prop is defined or until deferFn is called via run.</p>
  </Async.Deferred>
</Async>
```

**Comment by ghengeveld** [comment]
Excellent suggestion, never thought of that one. Too bad v6 is already out the door. I'm hesitant to change this again in the future, but who knows.

Strictly speaking, `initial` also covers the scenario where Async is created *without* any promise/promiseFn/deferFn, and set for example `promise` later. As such this state is not necessary tied to `deferFn`. Technically we could add `deferred` for cases where `deferFn` is provided but not yet invoked, but I'm afraid that would fragment the API too much and I don't see the use case.

**Comment by dhurlburtusa** [comment]
I just thought of another: `Async.Absent`. 

```
<Async promise={this.props.promise}>
  <Async.Absent>
    <p>I am rendered until a promise prop is defined or until deferFn is called via run and a promise is returned. That is, I am rendered while the promise is absent.</p>
  </Async.Absent>
</Async>
```

Just another idea in case you decide you want to change the names of the helper components.

Shall I close this "issue"?

**Comment by ghengeveld** [comment]
Let's close this discussion and focus on potential extensibility options. I'm looking for use cases where that might be needed.
