### ISSUE TITLE
Confusing API / Missing documentation: run() resolves even if deferFn is rejected

### ISSUE THREAD

**Issue by 0xR** [ghengeveld/react-async#48]
My `deferFn` is rejected, however my `run()` call is resolved. `Run()` returns the `Error` which caused the rejection. This means that I have to check whether response is valid or an Error.

What I expect is the `run()` call to reject when `deferFn` rejects.

**Comment by ghengeveld** [comment]
See https://github.com/ghengeveld/react-async/pull/47

This is a work in progress.

**Comment by ghengeveld** [comment]
Closing in favor of #79. Docs have been updated to clearly indicate `run` returns a promise that always fulfills.
