### ISSUE TITLE
pass resource to run using useFetch

### ISSUE THREAD

**Issue by nnals** [ghengeveld/react-async#49]
hello,

thanks for this library, i enjoy using it very much so far!

i have a question regarding the following situation: i have an app that allows users to track github repos. there's an endpoint `POST http://localhost:4242/api/repositories/{owner}/{repositoryName}`. the user can change a toggle in a form telling whether he/she wants to see that repository in the dashboard. 

is it possible to only pass the base url instead of the whole resource to useFetch and supply resource and body to run? so something like this:

```js
const { data, error, isLoading, run: postRepository } = useFetch('http://localhost:4242/api/repositories', {
  headers: { Accept: "application/json" },
  method: 'POST'
})

const handleSave = ({ owner, repositoryName, active }) =>
  postRepository(`/${owner}/${repositoryName}`, { body: { active } })
```

thank you and have a good day!
nicolai

**Comment by ghengeveld** [comment]
`useFetch` is only a wrapper around the fetch API, which doesn't support setting a base URL and working with relative paths from there. I do not intend to extend the `useFetch` API with any more custom behavior. You can however use `useAsync` to do what you want. In that case just hook up fetch with useAsync yourself and deal with any custom logic like that there. Here's an example: https://github.com/ghengeveld/react-async/blob/master/examples/with-abortcontroller/src/index.js
You can use the `args` or `props` to pass your relative path and hardcode the base URL.
