### ISSUE TITLE
ie11 support

### ISSUE THREAD

**Issue by patrick-lai** [ghengeveld/react-async#51]
Suggestion, for the dist maybe babel it to not have arrow functions. Because this library wont work on ie11.

**Comment by ghengeveld** [comment]
Hi Patrick,

If you use Webpack or Rollup (anything that supports the `"module"` entry point in package.json) for your app, it should automatically pick up and transpile React Async as well, according to your own rules. We actually ship separate distributions for various target environments, including the original sources. This means we don't have a legacy ES5 distribution for older browsers. If you need it, you can build it from source. `create-react-app` should do that out of the box.
