### ISSUE TITLE
[feat] Add reset render props to go back to initial state

### ISSUE THREAD

**Issue by whengely** [ghengeveld/react-async#58]
If I missed this in the docs, my apologies.

I have a scenario with a form where I want to be able to submit it multiple times but I can't seem to figure out how to get it back to the initial state.  

I put up a quick example here just to show what I'd like.

https://codesandbox.io/embed/react-typescript-pktsm

**Comment by ghengeveld** [comment]
Right now there's no way you can ever go back to the `initial` state, besides replacing the whole thing with a new instance of Async. We could add a `reinitialize` method to allow this, but you can also just make the form appear based on other state (ignoring `status`), such as one that you create yourself. E.g. you have a `isSubmitted` state value somewhere which you use to show/hide the form, and then you can reset that yourself when clicking the "submit another" button.

**Comment by noelyoo** [comment]
Hi, I was OK without the `reinitialize` feature since I took the same approach as @ghengeveld mentioned. But, I tried to find the `reinitialize` feature at first as @whengely did. Hence I think this is good to have.

I might open a PR for this when I find some time.

**Comment by ghengeveld** [comment]
Go for it 💪

**Comment by noelyoo** [comment]
After some discussion, I found the `reinitialize` feature was different from what I thought so I closed the PR https://github.com/ghengeveld/react-async/pull/62.

I made a small custom hook, as a simple reference, which was I wanted.
- Storybook: https://noelyoo.github.io/use-async-fn/?path=/story/asyncfn--promisefn
- Github: https://github.com/noelyoo/use-async-fn

I think this can be useful for someone in some context.

**Comment by ghengeveld** [comment]
Closing the issue because this is achievable by other means as described above.
