### ISSUE TITLE
Support `async void` functions - currently they go from `Pending` to `Initial`, never reaching `Fulfilled`

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-clarksons** [ghengeveld/react-async#60]
CAVEAT: This is the behavior I observed in 5.0 which we're temporarily stuck with, and could not find a mention of it in the changelog, hence raising it here. Feel free to close if this is fixed in the current 7.X.

Problem: If my function is:

```
async function delete() {
  someStuff();
  await someRestClient.delete(...);
  someLogicButNoReturn();
}
```
and I want to use Async for showing progress, success and error of it like:
```
<Async promiseFn={delete}>
<Initial>
    <button onClick={delete}>Delete</button>
</Initial>
<Pending state={state}>Deleting...</Pending>
<Fulfilled>
    Success!
</Fulfilled>
<Rejected>
    Error! ...
</Initial>
</Async>
```

then a successful run of that function (Promise getting resolved) will actually never reach the `<Fulfilled>`. It will go back to the `<Initial>` state.
A current workaround is to have the `delete` function return `null` at the end, but it doesn't seem right to ignore the fact that the Promise is resolved, just because it resolved to `undefined`. It did resolve, it is successful, which means it's no longer pending or initial, and `Fulfilled` is the best state to describe a successful run.

If this suggestion is accepted, It's then probably worth to update the documentation [here](https://github.com/ghengeveld/react-async#fulfilled--asyncfulfilled) to no longer say that `<Fulfilled>` it has any interpretation of the data - `<Fulfilled>` should only talk about status of the Promise being 'resolved'.

**Considerations about backwards compatibility:**
I don't think this is a breaking change, because it seems to me that any usage would rely on such a quirk - actual resolved promises leaving an initial state to the user. I feel the issue just didn't surface before, because non-void functions are probably predominant use of this library. For void functions, the change is only to the benefit. They can now be written non-idiomatically as functions with no return.
If there are valid concers I have missed, please perhaps consider implementing the change in an 'opt in' fashion, so it is possible to not require the operation logic code contain any workarounds required solely by the presentation layer - the `render` method.

**Comment by ghengeveld** [comment]
This was actually [changed and released in v6.0.2](https://github.com/ghengeveld/react-async/compare/v6.0.1...v6.0.2#diff-149b30fde0306e461dc519d4853f1e50R230).

Why are you stuck on v5?

**Comment by slawomir-brzezinski-at-clarksons** [comment]
> This was actually changed and released in v6.0.2.

Great. Sorry for bothering then... Or... well... perhaps worth updating these places in the readme.

> Why are you stuck on v5?

Well, shouldn't have said stuck, sorry. Just had no time to consider the update - I forgot you left the aliases to make upgrade not require any change of code (🤦‍♂), but also made a guess that it's not worth doing it now but only after raising this, based on the documentation making it look like the behavior's still there.

If the behavior is fixed, that's another good reason to update then 😄
I will do that first thing next week and can confirm and close, or you can close the issue if you feel this is for certain (still consider the docs update :) ).
Cheers!

**Comment by ghengeveld** [comment]
Done: https://github.com/ghengeveld/react-async/commit/fdee7a5e2e06bf5a8c3873593a154b69b179abc5

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Works on our end too. Thanks again!
