### ISSUE TITLE
"TypeError: root is not an Object" in react-native@0.59

### ISSUE THREAD

**Issue by hkaju** [ghengeveld/react-async#65]
We're trying to use `react-async` in a React Native project and getting an immediate red screen with `TypeError: root is not an Object`. This gets thrown from  https://github.com/ghengeveld/react-async/blob/a1aa8231ad631b6edc98a73f2a9abdec8ed70681/packages/react-async/src/useAsync.js#L54 

We've traced the issue back to https://github.com/ghengeveld/react-async/blob/a1aa8231ad631b6edc98a73f2a9abdec8ed70681/packages/react-async/src/useAsync.js#L7 that does not resolve to `global` for some reason. If I remove the circular reference check `global.global === global` the error goes away but I don't know if that's quite correct.

Looks like this was introduced in https://github.com/ghengeveld/react-async/commit/c5a4e09c1edda2619ad88ccb8216ab2faf629ebe

**Comment by hkaju** [comment]
Downgrade to `7.0.1` gets rid of the error too.

**Comment by ghengeveld** [comment]
Clearly, what fixed an issue in Node.js has broken it in React Native. This will require some work to get it right. Do you know how React Native usually deals with globals?

**Comment by ghengeveld** [comment]
React Native apparently [expects `global.GLOBAL`](https://github.com/facebook/react-native/blob/master/Libraries/Core/setUpGlobals.js) in all caps. I think omitting the check is fine, but a nicer way would be to add the all caps alternative to the condition.

**Comment by ghengeveld** [comment]
Fixed in [v7.0.5](https://github.com/ghengeveld/react-async/releases/tag/react-async%407.0.5).

**Comment by novemberborn** [comment]
@ghengeveld I don't see 7.0.5 on npm: https://www.npmjs.com/package/react-async

**Comment by ghengeveld** [comment]
Thanks for letting me know! Forgot to do the actual npm publish. It's there now 👍
