### ISSUE TITLE
can this work in an onclick handler with contextual data

### ISSUE THREAD

**Issue by dagda1** [ghengeveld/react-async#66]
I take it this cannot work from an onclick handler like this:

say the event hanlder call this function:

```
export async function getAllSites(businessId: string) {
  const url = createSiteUrl(businessId);
```

So the buinessId argument is coming from an autocomplete, and this is appended onto the url.   But with react-async I have to create the url up front unless I am missing something.

Is there a way this could work with dynamic urls or dynamic values?

**Comment by ghengeveld** [comment]
The URL can certainly be dynamic, like this:

```js
const loadUser = ({ userId }) =>
  fetch(`https://reqres.in/api/users/${userId}`)
    .then(res => (res.ok ? res : Promise.reject(res)))
    .then(res => res.json())
```

Then in your render:

```jsx
<Async promiseFn={loadUser} userId={1}>
  {({ data, error, isPending }) => {
    if (isPending) return <UserPlaceholder />
    if (error) return <p>{error.message}</p>
    if (data) return <UserDetails data={data} />
    return null
  }}
</Async>
```

See https://github.com/ghengeveld/react-async/blob/master/examples/basic-fetch/src/index.js for the whole thing.

Any props that you pass to `<Async>` will be passed to your async function (1st arg for `promiseFn`, 2nd arg for `deferFn`). In your case, you would need to change `getAllSites` to accept an object:

```js
export async function getAllSites({ businessId: string }) { ... }
```

Then pass `businessId` as a prop to `<Async>`: 

```jsx
<Async promiseFn={getAllSites} businessId={1}>
  ...
</Async>
```

This works similarly with `useAsync`:

```js
const { data, error, isPending } = useAsync({ promiseFn: getAllSites, businessId: 1 }) 
```

**Comment by pennjlin** [comment]
@ghengeveld related to this issue, what if my `userId` is passed from parent as a prop which is fetched asynchronously, and I only want `promiseFn` to execute the request when `props.userId` is not null? I tried using conditionals but it breaks the rule of hooks, and I would rather have `react-async` return `isPending` while `userId = null`. Thanks for helping! 

Update: what I'm seeing right now, is that my `promiseFn` errors out and will not reattempt when `userId` is not null anymore.

**Comment by pennjlin** [comment]
> @ghengeveld related to this issue, what if my `userId` is passed from parent as a prop which is fetched asynchronously, and I only want `promiseFn` to execute the request when `props.userId` is not null? I tried using conditionals but it breaks the rule of hooks, and I would rather have `react-async` return `isPending` while `userId = null`. Thanks for helping!
> 
> Update: what I'm seeing right now, is that my `promiseFn` errors out and will not reattempt when `userId` is not null anymore.

Nevermind this is fixed. Upon inspection, there's a `watch` option variable that does exactly this. Thanks!
