### ISSUE TITLE
promiseFn is called only once even if argument has changed

### ISSUE THREAD

**Issue by gabyrusu** [ghengeveld/react-async#67]
react: 16.8.6
react-async: 7.0.4
react-router-dom: 5.0.1 

Hi guys, I have the following problem: 

```
<BrowserRouter>
    <Nav>
        <NavLink to="/">Home</NavLink>
        <NavLink to="/page/about">About</NavLink>
        <NavLink to="/page/contact">Contact</NavLink>                
    </Nav>
    <Switch>
        <Route exact path="/" component={Home} />
        <Route exact path="/page/:slug" component={Page} />
    </Switch>
</BrowserRouter>
```

Then in my Page component:

```
...
const getPage = ({ pageId }: { pageId: string }) => {
    return new Promise((resolve, reject) => {
        resolve(pageId);
    });
};

const Page = ({ match }: { match: any }) => {
    const { data, isPending, isRejected, isResolved, error } = useAsync({
        promiseFn: getPage,
        pageId   : match.params.slug
    } as any);
...
```

When navigating from Home to About or Contact all works fine: getPage is called every time, BUT when navigating from About to Contact and viceversa getPage is called only the first time, like it has no idea that "pageId" has changed.

This works perfectly fine though:

```
const pageId = match.params.slug;
const [isPending, setIsPending] = React.useState(false);
const [error, setError] = React.useState(null) as any;
const [data, setData] = React.useState(null) as any;

useEffect(() => {
        setIsPending(true);
        getPage({ pageId }).then(data => {
            setIsPending(false);
            setData(data);
            setError(null);
        }).catch(e => {
            setIsPending(false);
            setError(e);
            setData(null);
        });
}, [pageId, setData, setError]);
```

Am I missing something? I really can't figure this out.

Thank you!

**Comment by ghengeveld** [comment]
Navigating from Home to About/Contact makes it render a different component (Home or Page), hence triggering `getPage`, while navigating from About to Contact will stay in the same Page component, just with different props. This is how React works (it tries to reuse as much as possible). 

React Async will not reload your promiseFn when a prop changes, you'll have to tell it to do that. You can do so by providing  `watch={match.params.slug}`, so it will reload when the slug changes.

**Comment by gabyrusu** [comment]
Thank you @ghengeveld! I will try and let you know.
