### ISSUE TITLE
feature request for v8.0.0 - return array instead of object

### ISSUE THREAD

**Issue by keeganstothert** [ghengeveld/react-async#84]
i would love this

```js
const [isLoadingBigThings, bigThingsError, BigThings, fetchBigThings] = useAsync(
  {
    deferFn: getBigThings,
  },
  { asArray: true }
);
const [isLoadingSmallThings, SmallThingsError, SmallThings, fetchSmallThings] = useAsync(
  {
    deferFn: getSmallThings,
  },
  { asArray: true }
);
```

**Comment by ghengeveld** [comment]
Could you elaborate why? IIRC there are currently 14 props on the returned object, putting that in an array is very unwieldy.

**Comment by keeganstothert** [comment]
yea because when i perform multiple I have to go 

```js
const { isLoading: isLoadingBigThings, ...}
const { isLoading: isLoadingSmallThings, ...}
```

**Comment by ghengeveld** [comment]
Why not this?

```
const bigThing = useAsync(...)

if (bigThing.isLoading) ...
```

Less code is not necessarily better code. I'm not going to make a breaking change with significant impact just because it allows one to write a little less code in a specific situation. Especially if there are major downsides (arrays suck for this use case) and an easy workaround.
