### ISSUE TITLE
deferFn always resolves `false`

### ISSUE THREAD

**Issue by wyqydsyq** [ghengeveld/react-async#87]
deferFn should resolve the value of it's underlying promise, however it actually always resolves `false`:

```ts
	const { data, run, setData } = useAsync({
		initialValue: defaultContext,
		deferFn: customerLogin,
	});

	if (doLogin) {
		run(customerId).then(console.log);
	}
```

Logs `false`.

I would expect to get the object resolved by the Promise that `customerLogin` returns.

I want to be able to extract the value from the promise `deferFn` resolves, then call `setData` with the resolved response so the component re-renders with the new data e.g.

```ts
	const { data, run, setData } = useAsync({
		initialValue: defaultContext,
		deferFn: customerLogin,
	});

	if (doLogin) {
		run(customerId).then(customer => setData(customer));
	}
```

I need to use `deferFn` because I only want to run the promise conditionally, `promiseFn` (which does return the resolved value as expected) executes automatically so wouldn't work here, but I also want to get the data resolved from the deferred promise as well.

**Comment by ghengeveld** [comment]
This is actually going to change in the next release, and should resolve your issue. See https://github.com/ghengeveld/react-async/pull/83

In a nutshell:
- `run` no longer returns anything
- a new `promise` property is introduced, which properly resolves/rejects as expected

Regardless, you shouldn't need this at all. If you `run` a deferFn, it's fulfilled value will automatically become the `data`. You don't need `setData` to do that.

**Comment by ghengeveld** [comment]
I'm going to close this because it should be resolved by either relying on `run` to update `data` automatically, or by using the newly introduced `promise` property returned by `useAsync`.
